### ISSUE TITLE
Process Hang Detection on Gameservers

### ISSUE THREAD

**Issue by uaon** [7Cav/service-level-configs#53]
Currently we do not have a reliable way to detect process hang on gameservers.
From testing via Extension we can either watch threads or use memory usage sum to check if a process has hanged. This works to a point but requires adds more complications where updates to CBA_A3/ XEH events could break functionality or cause adverse results. 

However,
Via Memory we can check via PS to get results on the memory usage and take a snapshot.
`function Get-ChildProcessMemoryUsage {
    param(
        $ID=$PID,
        [int]$res=0
    )
    Get-WmiObject -Class Win32_Process -Filter "ParentProcessID=$ID" | % { 
        if($_.ProcessID -ne $null) {
            $proc = Get-Process -ID $_.ProcessID -ErrorAction SilentlyContinue
            $res += $proc.PrivateMemorySize + $proc.WorkingSet
            $res += (Get-ChildProcessMemoryUsage $_.ProcessID $res)
        }
    }
    $res
}`

We could take the memory count for each child process and compare snapshots to see the gap if the snapshots are the same within a ~2 minute~ period, we could assume that the process is in a hung state.

**Comment by BojanOnTheInternet** [comment]
With the CavMetrics addon you are push metrics from the server into your time-series database. These metrics should stop reporting once the process hangs.

Perhaps you can look at the time since the last log, or even configure Grafana to alert based on that and send a webhook to automatically restart.
