### ISSUE TITLE
Performance and Profiling Binary testing

### ISSUE THREAD

**Issue by uaon** [7Cav/service-level-configs#61]
With the addition of Profiling and Performance binaries released for ARMA 3, we can see if server performance is improved by using them.

Notes from Latest Release
- Added: Linux server 64-bit
- Added: Config setting to configure the Steam Query limit (limitation of the mod list in Launcher) - FT-T123655
- Fixed: Inability to store Code type variables in profileNamespace ("Global namespace not passed during" error in RPT)
- Fixed: Freeze related to UI Control creation - FT-T136596
- Fixed: Inability to spawn P3Ds inside a scenario file via createSimpleObject - FT-T147191
- Fixed: Server crash when trying to load a scenario with a dot in its filename - FT-T150767
- Fixed: Squad/Arma 3 Units logo not showing up on Linux servers - FT-T80864, FT-T136477
- Tweaked: Security improvements concerning Headless Clients
- Tweaked: Forced whitelisting of 127.0.0.1 in headlessClients[]
- Tweaked: Stability improvements
- Tweaked: Performance improvements on network processing in MP versus AI

It's been noted that setting -FPSlimit actually improves stability for longer periods. setting this too high increases instability on large servers.

Network traffic for AI being "valid" was another potential performance increasing fix brought into this update.

Download is located here:
https://drive.google.com/drive/u/0/folders/1ucBXw0LiRPjIAuHItgund6YQlM27E5ns

**Comment by uaon** [comment]
performance binary removed from tact 2

**Comment by uaon** [comment]
add performance binary to development 1, testing continued.

**Comment by uaon** [comment]
Removed from Development 1

--
Discussion made on using this in more permanent basis
Training Server 1, Dev 2

**Comment by uaon** [comment]
Added Performance Binary
`arma3server_performance_x64_198_146445_v06`

- Training Server 1
- Development 2

**Comment by davidcit646** [comment]
We have already noticed marked improvements over the previous profile. Signature mis-match has now been resolved and is allowing individual players to join by using the launcher.

For best results, I highly recommend that we immediately put this profile onto Tac2.

**Comment by uaon** [comment]
Noticing a trend, with the Prof Binary, people have become dependant on the launcher to automatically configure and load into game, when it was pulled from Tact 2, players were confused why the game wasn't allowing them to join.

**Comment by uaon** [comment]
Lost Traction on this over the month.
Need to setup another pull request with feature to implement persistent way of using performance binary without worrying about steamcmd overwriting the file.

- arma3server_performance_x64_198_146445_v06

**Comment by uaon** [comment]
[commit 0c8a6f3](https://github.com/7Cav/service-level-configs/commit/0c8a6f32f48b12b998542afe3c969ec75f8c1418)



- [ ] -limitFPS=30 
- [ ] tbb4malloc_x64
- [ ] -hugepages

**Comment by uaon** [comment]
Closing
