### ISSUE TITLE
ARMA 3 - Automation for Server Side Scripts and Patching

### ISSUE THREAD

**Issue by uaon** [7Cav/service-level-configs#78]
- Ability to manage additional files or patches onto the server.
- Identify limitations of patching arma servers and prepare SOP going forward.
- Add to or create new update process to allow for patching.

**Comment by ColdEvul** [comment]
Can a workshop subscription be valid?

**Comment by uaon** [comment]
So,
`https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1/?&itemcount=1&publishedfileids%5B0%5D=498740884`

With above, we can see details on workshop items, using the **ISteamRemoteStorage/**
This *could be used to compare against and run a daemon to check status at a interval. Or we could make a hash map of the mods running on each instance and check promise on `"time_updated":1592766074`

`http://api.steampowered.com/ISteamUserStats/GetSchemaForGame/v2/?key={STEAM_API_KEY}&appid=107410&format=json`
And with this we can pull information on the game, possibly do the same here but without the need to hash map it since its only one item.

Further on, we still need a implementation that takes known patches for our addons and settings ( cba_settings ) and puts them into the mod folder after a update. Due to the nature of steamcmd, since this overwrites the directory and its contents depending on diff, its removing any files or modifications within when it doesn't match with whats on the workshop for said addon.

This and including a better way to move configuration and extra "addon" sqf/sqs/fsm files to be used, such as those we use in directories within the ARMA 3 installation path -e.g.  `./serverside/zeus_permissions/mypermissions.sqf` that need to be outside the mission/addon for easy changes.
